export const cards1 = [
  {
    preview: 'cards-1-h-1.jpg',
    original: 'cards-1-h-1.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-2.jpg',
    original: 'cards-1-h-2.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-3.jpg',
    original: 'cards-1-h-3.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-4.jpg',
    original: 'cards-1-h-4.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-5.jpg',
    original: 'cards-1-h-5.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-6.jpg',
    original: 'cards-1-h-6.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-7.jpg',
    original: 'cards-1-h-7.jpg',
    description: 'Открытка 1',
  },
  {
    preview: 'cards-1-h-8.jpg',
    original: 'cards-1-h-8.jpg',
    description: 'Открытка 1',
  },
];

export const cards2 = [
  { preview: 'cards-2-v-1-prev.jpg', original: 'cards-2-v-1.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-2-prev.jpg', original: 'cards-2-v-2.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-3-prev.jpg', original: 'cards-2-v-3.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-4-prev.jpg', original: 'cards-2-v-4.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-5-prev.jpg', original: 'cards-2-v-5.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-6-prev.jpg', original: 'cards-2-v-6.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-7-prev.jpg', original: 'cards-2-v-7.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-8-prev.jpg', original: 'cards-2-v-8.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-9-prev.jpg', original: 'cards-2-v-9.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-10-prev.jpg', original: 'cards-2-v-10.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-11-prev.jpg', original: 'cards-2-v-11.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-12-prev.jpg', original: 'cards-2-v-12.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-13-prev.jpg', original: 'cards-2-v-13.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-14-prev.jpg', original: 'cards-2-v-14.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-15-prev.jpg', original: 'cards-2-v-15.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-16-prev.jpg', original: 'cards-2-v-16.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-17-prev.jpg', original: 'cards-2-v-17.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-18-prev.jpg', original: 'cards-2-v-18.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-19-prev.jpg', original: 'cards-2-v-19.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-20-prev.jpg', original: 'cards-2-v-20.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-v-21-prev.jpg', original: 'cards-2-v-21.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-h-1-prev.jpg', original: 'cards-2-h-1.jpg', description: 'Открытка 2' },
  { preview: 'cards-2-h-2-prev.jpg', original: 'cards-2-h-2.jpg', description: 'Открытка 2' },
];

export const cards4 = [
  { preview: 'cards-4-h-1-prev.jpg', original: 'cards-4-h-1.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-2-prev.jpg', original: 'cards-4-h-2.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-3-prev.jpg', original: 'cards-4-h-3.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-4-prev.jpg', original: 'cards-4-h-4.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-5-prev.jpg', original: 'cards-4-h-5.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-6-prev.jpg', original: 'cards-4-h-6.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-7-prev.jpg', original: 'cards-4-h-7.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-8-prev.jpg', original: 'cards-4-h-8.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-9-prev.jpg', original: 'cards-4-h-9.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-10-prev.jpg', original: 'cards-4-h-10.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-11-prev.jpg', original: 'cards-4-h-11.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-h-12-prev.jpg', original: 'cards-4-h-12.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-v-1-prev.jpg', original: 'cards-4-v-1.jpg', description: 'Открытка 4' },
  { preview: 'cards-4-v-2-prev.jpg', original: 'cards-4-v-2.jpg', description: 'Открытка 4' },
];

export const cards5 = [
  { preview: 'cards-5-h-1-prev.jpg', original: 'cards-5-h-1.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-h-2-prev.jpg', original: 'cards-5-h-2.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-h-3-prev.jpg', original: 'cards-5-h-3.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-h-4-prev.jpg', original: 'cards-5-h-4.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-h-5-prev.jpg', original: 'cards-5-h-5.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-h-6-prev.jpg', original: 'cards-5-h-6.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-v-1-prev.jpg', original: 'cards-5-v-1.jpg', description: 'Открытка 5' },
  { preview: 'cards-5-v-2-prev.jpg', original: 'cards-5-v-2.jpg', description: 'Открытка 5' },
];

export const cards6 = [
  { preview: 'cards-6-h-1-prev.jpg', original: 'cards-6-h-1.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-h-2-prev.jpg', original: 'cards-6-h-2.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-h-3-prev.jpg', original: 'cards-6-h-3.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-h-4-prev.jpg', original: 'cards-6-h-4.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-h-5-prev.jpg', original: 'cards-6-h-5.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-h-6-prev.jpg', original: 'cards-6-h-6.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-1-prev.jpg', original: 'cards-6-v-1.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-2-prev.jpg', original: 'cards-6-v-2.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-3-prev.jpg', original: 'cards-6-v-3.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-4-prev.jpg', original: 'cards-6-v-4.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-5-prev.jpg', original: 'cards-6-v-5.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-6-prev.jpg', original: 'cards-6-v-6.jpg', description: 'Открытка 6' },
  { preview: 'cards-6-v-7-prev.jpg', original: 'cards-6-v-7.jpg', description: 'Открытка 6' },
];

export const cards7 = [
  { preview: 'cards-7-h-1-prev.jpg', original: 'cards-7-h-1.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-h-2-prev.jpg', original: 'cards-7-h-2.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-1-prev.jpg', original: 'cards-7-v-1.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-2-prev.jpg', original: 'cards-7-v-2.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-3-prev.jpg', original: 'cards-7-v-3.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-4-prev.jpg', original: 'cards-7-v-4.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-5-prev.jpg', original: 'cards-7-v-5.jpg', description: 'Открытка 7' },
  { preview: 'cards-7-v-6-prev.jpg', original: 'cards-7-v-6.jpg', description: 'Открытка 7' },
];

export const cards8 = [
  { preview: 'cards-8-h-1-prev.jpg', original: 'cards-8-h-1.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-2-prev.jpg', original: 'cards-8-h-2.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-3-prev.jpg', original: 'cards-8-h-3.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-4-prev.jpg', original: 'cards-8-h-4.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-5-prev.jpg', original: 'cards-8-h-5.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-6-prev.jpg', original: 'cards-8-h-6.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-7-prev.jpg', original: 'cards-8-h-7.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-8-prev.jpg', original: 'cards-8-h-8.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-9-prev.jpg', original: 'cards-8-h-9.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-10-prev.jpg', original: 'cards-8-h-10.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-h-11-prev.jpg', original: 'cards-8-h-11.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-v-1-prev.jpg', original: 'cards-8-v-1.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-v-2-prev.jpg', original: 'cards-8-v-2.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-v-3-prev.jpg', original: 'cards-8-v-3.jpg', description: 'Открытка 8' },
  { preview: 'cards-8-v-4-prev.jpg', original: 'cards-8-v-4.jpg', description: 'Открытка 8' },
];

export const cards9 = [
  { preview: 'cards-9-h-1-prev.jpg', original: 'cards-9-h-1.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-h-2-prev.jpg', original: 'cards-9-h-2.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-h-3-prev.jpg', original: 'cards-9-h-3.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-h-4-prev.jpg', original: 'cards-9-h-4.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-h-5-prev.jpg', original: 'cards-9-h-5.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-v-1-prev.jpg', original: 'cards-9-v-1.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-v-2-prev.jpg', original: 'cards-9-v-2.jpg', description: 'Открытка 9' },
  { preview: 'cards-9-v-3-prev.jpg', original: 'cards-9-v-3.jpg', description: 'Открытка 9' },
];

export const cards10 = [
  { preview: 'cards-10-h-1-prev.jpg', original: 'cards-10-h-1.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-h-2-prev.jpg', original: 'cards-10-h-2.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-h-3-prev.jpg', original: 'cards-10-h-3.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-1-prev.jpg', original: 'cards-10-v-1.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-2-prev.jpg', original: 'cards-10-v-2.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-3-prev.jpg', original: 'cards-10-v-3.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-4-prev.jpg', original: 'cards-10-v-4.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-5-prev.jpg', original: 'cards-10-v-5.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-6-prev.jpg', original: 'cards-10-v-6.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-7-prev.jpg', original: 'cards-10-v-7.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-8-prev.jpg', original: 'cards-10-v-8.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-9-prev.jpg', original: 'cards-10-v-9.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-10-prev.jpg', original: 'cards-10-v-10.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-11-prev.jpg', original: 'cards-10-v-11.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-12-prev.jpg', original: 'cards-10-v-12.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-13-prev.jpg', original: 'cards-10-v-13.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-14-prev.jpg', original: 'cards-10-v-14.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-15-prev.jpg', original: 'cards-10-v-15.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-16-prev.jpg', original: 'cards-10-v-16.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-17-prev.jpg', original: 'cards-10-v-17.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-18-prev.jpg', original: 'cards-10-v-18.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-19-prev.jpg', original: 'cards-10-v-19.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-20-prev.jpg', original: 'cards-10-v-20.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-21-prev.jpg', original: 'cards-10-v-21.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-22-prev.jpg', original: 'cards-10-v-22.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-23-prev.jpg', original: 'cards-10-v-23.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-24-prev.jpg', original: 'cards-10-v-24.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-25-prev.jpg', original: 'cards-10-v-25.jpg', description: 'Открытка 10' },
  { preview: 'cards-10-v-26-prev.jpg', original: 'cards-10-v-26.jpg', description: 'Открытка 10' },
];
10;
